from datetime import datetime

ZONES = {
    "back_alley": {
        "name": "Back Alley",
        "unlock_level": 1,
        "description": "Soggy boxes, lost sneakers, and low-tier treasure.",
        "banner": "🗑️ ╔═ BACK ALLEY ═╗",
        "unicode_style": "⌁ damp / shady / beginner luck ⌁",
        "danger": "Low",
        "luck": "Slightly cursed",
        "image": "assets/zones/back_alley.png",
    },
    "apartment_bins": {
        "name": "Apartment Bins",
        "unlock_level": 3,
        "description": "Household leftovers, mystery decor, and weird little jackpots.",
        "banner": "🏢 ╔═ APARTMENT BINS ═╗",
        "unicode_style": "✦ domestic chaos / hidden jackpots ✦",
        "danger": "Medium",
        "luck": "Nosy gremlin good",
        "image": "assets/zones/apartment_bins.png",
    },
    "restaurant_dumpster": {
        "name": "Restaurant Dumpster",
        "unlock_level": 5,
        "description": "Greasy chaos, cursed leftovers, and surprisingly good loot.",
        "banner": "🍔 ╔═ RESTAURANT DUMPSTER ═╗",
        "unicode_style": "⚠ greasy / loud / reward-heavy ⚠",
        "danger": "Medium",
        "luck": "Suspiciously tasty",
        "image": "assets/zones/restaurant_dumpster.png",
    },
    "mall_rear_lot": {
        "name": "Mall Rear Lot",
        "unlock_level": 8,
        "description": "Discarded fashion, promo junk, and elite trash energy.",
        "banner": "🛍️ ╔═ MALL REAR LOT ═╗",
        "unicode_style": "⟡ glossy / expensive / high-tier rot ⟡",
        "danger": "High",
        "luck": "Luxury filth",
        "image": "assets/zones/mall_rear_lot.png",
    },
}

EQUIP_SLOTS = ["head", "body", "hands", "feet", "accessory"]

ITEMS = {
    "old_shoe": {
        "name": "Old Shoe",
        "rarity": "Common",
        "kind": "junk",
        "coins": 5,
        "xp": 5,
        "zone_ids": ["back_alley"],
        "image": "assets/items/old_shoe.png",
        "emoji": "👟",
        "flavor": "Still has main character energy somehow.",
        "pawnable": True,
    },
    "scrap_metal": {
        "name": "Scrap Metal",
        "rarity": "Common",
        "kind": "junk",
        "coins": 10,
        "xp": 7,
        "zone_ids": ["back_alley", "apartment_bins"],
        "image": "assets/items/scrap_metal.png",
        "emoji": "🔩",
        "flavor": "Rusty, crunchy, and weirdly valuable.",
        "pawnable": True,
    },
    "broken_phone": {
        "name": "Broken Phone",
        "rarity": "Rare",
        "kind": "junk",
        "coins": 25,
        "xp": 20,
        "zone_ids": ["apartment_bins"],
        "image": "assets/items/broken_phone.png",
        "emoji": "📱",
        "flavor": "Screen destroyed. Aura intact.",
        "pawnable": True,
    },
    "mystery_box": {
        "name": "Mystery Box",
        "rarity": "Epic",
        "kind": "junk",
        "coins": 50,
        "xp": 35,
        "zone_ids": ["restaurant_dumpster", "mall_rear_lot"],
        "image": "assets/items/mystery_box.png",
        "emoji": "🎁",
        "flavor": "Suspicious. Glorious. Probably unstable.",
        "pawnable": True,
    },
    "trash_crown": {
        "name": "Trash Crown",
        "rarity": "Legendary",
        "kind": "artifact",
        "coins": 0,
        "xp": 60,
        "zone_ids": ["mall_rear_lot"],
        "image": "assets/items/trash_crown.png",
        "emoji": "👑",
        "flavor": "Proof that garbage can, in fact, be royalty.",
        "pawnable": False,
        "museum": True,
    },

    "scuffed_plastic_shard": {
        "name": "Scuffed Plastic Shard",
        "rarity": "Common",
        "kind": "junk",
        "coins": 6,
        "xp": 4,
        "zone_ids": ["back_alley"],
        "image": "assets/items/scuffed_plastic_shard.png",
        "emoji": "🧩",
        "flavor": "Barely useful. Still pocketed immediately.",
        "pawnable": True,
    },
    "cracked_wire_bundle": {
        "name": "Cracked Wire Bundle",
        "rarity": "Common",
        "kind": "junk",
        "coins": 8,
        "xp": 5,
        "zone_ids": ["back_alley", "apartment_bins"],
        "image": "assets/items/cracked_wire_bundle.png",
        "emoji": "🪢",
        "flavor": "Looks dangerous. Feels profitable.",
        "pawnable": True,
    },
    "dusty_gear_chunk": {
        "name": "Dusty Gear Chunk",
        "rarity": "Common",
        "kind": "junk",
        "coins": 7,
        "xp": 5,
        "zone_ids": ["back_alley", "apartment_bins"],
        "image": "assets/items/dusty_gear_chunk.png",
        "emoji": "⚙️",
        "flavor": "Machine ancestry unknown.",
        "pawnable": True,
    },
    "melted_trinket": {
        "name": "Melted Trinket",
        "rarity": "Common",
        "kind": "junk",
        "coins": 9,
        "xp": 6,
        "zone_ids": ["apartment_bins", "restaurant_dumpster"],
        "image": "assets/items/melted_trinket.png",
        "emoji": "🫠",
        "flavor": "Something fancy died for this.",
        "pawnable": True,
    },
    "burnt_sludge": {
        "name": "Burnt Sludge",
        "rarity": "Rare",
        "kind": "event",
        "coins": 45,
        "xp": 18,
        "zone_ids": ["restaurant_dumpster"],
        "image": "assets/items/burnt_sludge.png",
        "emoji": "🔥",
        "flavor": "Warm, cursed, and somehow collectible.",
        "pawnable": True,
    },

    "bent_nail_cluster": {
        "name": "Bent Nail Cluster",
        "rarity": "Common",
        "kind": "material",
        "coins": 11,
        "xp": 7,
        "zone_ids": ["back_alley", "apartment_bins"],
        "image": "assets/items/bent_nail_cluster.png",
        "emoji": "📎",
        "flavor": "A handful of tetanus and ambition.",
        "pawnable": True,
    },
    "compressed_scrap_cube": {
        "name": "Compressed Scrap Cube",
        "rarity": "Uncommon",
        "kind": "material",
        "coins": 18,
        "xp": 10,
        "zone_ids": ["apartment_bins", "restaurant_dumpster"],
        "image": "assets/items/compressed_scrap_cube.png",
        "emoji": "🧊",
        "flavor": "Dense little goblin engineering.",
        "pawnable": True,
    },
    "bent_circuit": {
        "name": "Bent Circuit",
        "rarity": "Uncommon",
        "kind": "material",
        "coins": 20,
        "xp": 12,
        "zone_ids": ["apartment_bins", "restaurant_dumpster"],
        "image": "assets/items/bent_circuit.png",
        "emoji": "💾",
        "flavor": "Still looks smarter than most people.",
        "pawnable": True,
    },
    "balance_chip": {
        "name": "Balance Chip",
        "rarity": "Rare",
        "kind": "material",
        "coins": 26,
        "xp": 15,
        "zone_ids": ["apartment_bins", "mall_rear_lot"],
        "image": "assets/items/balance_chip.png",
        "emoji": "🎛️",
        "flavor": "Keeps one thing stable. Nobody knows what.",
        "pawnable": True,
    },
    "bonus_socket": {
        "name": "Bonus Socket",
        "rarity": "Rare",
        "kind": "material",
        "coins": 24,
        "xp": 14,
        "zone_ids": ["apartment_bins", "mall_rear_lot"],
        "image": "assets/items/bonus_socket.png",
        "emoji": "🔌",
        "flavor": "Looks like it belongs to something overpowered.",
        "pawnable": True,
    },
    "distorted_battery": {
        "name": "Distorted Battery",
        "rarity": "Rare",
        "kind": "material",
        "coins": 28,
        "xp": 16,
        "zone_ids": ["restaurant_dumpster", "mall_rear_lot"],
        "image": "assets/items/distorted_battery.png",
        "emoji": "🔋",
        "flavor": "It hums in a threatening way.",
        "pawnable": True,
    },
    "foam_insulator": {
        "name": "Foam Insulator",
        "rarity": "Uncommon",
        "kind": "material",
        "coins": 16,
        "xp": 9,
        "zone_ids": ["apartment_bins", "restaurant_dumpster"],
        "image": "assets/items/foam_insulator.png",
        "emoji": "🧽",
        "flavor": "Lightweight, ugly, useful.",
        "pawnable": True,
    },
    "glitch_resin": {
        "name": "Glitch Resin",
        "rarity": "Rare",
        "kind": "material",
        "coins": 32,
        "xp": 18,
        "zone_ids": ["restaurant_dumpster", "mall_rear_lot"],
        "image": "assets/items/glitch_resin.png",
        "emoji": "🫧",
        "flavor": "Sticky reality error in liquid form.",
        "pawnable": True,
    },
    "neon_relay": {
        "name": "Neon Relay",
        "rarity": "Rare",
        "kind": "material",
        "coins": 30,
        "xp": 18,
        "zone_ids": ["mall_rear_lot"],
        "image": "assets/items/neon_relay.png",
        "emoji": "💡",
        "flavor": "Buzzing with expired mall energy.",
        "pawnable": True,
    },
    "neon_shard": {
        "name": "Neon Shard",
        "rarity": "Uncommon",
        "kind": "material",
        "coins": 19,
        "xp": 11,
        "zone_ids": ["restaurant_dumpster", "mall_rear_lot"],
        "image": "assets/items/neon_shard.png",
        "emoji": "🔷",
        "flavor": "Bright enough to feel illegal.",
        "pawnable": True,
    },
    "rustcore_plate": {
        "name": "Rustcore Plate",
        "rarity": "Uncommon",
        "kind": "material",
        "coins": 18,
        "xp": 10,
        "zone_ids": ["apartment_bins", "restaurant_dumpster"],
        "image": "assets/items/rustcore_plate.png",
        "emoji": "🛡️",
        "flavor": "Old metal with serious personality.",
        "pawnable": True,
    },
    "static_coil": {
        "name": "Static Coil",
        "rarity": "Rare",
        "kind": "material",
        "coins": 29,
        "xp": 17,
        "zone_ids": ["restaurant_dumpster", "mall_rear_lot"],
        "image": "assets/items/static_coil.png",
        "emoji": "🌀",
        "flavor": "Keeps crackling even when ignored.",
        "pawnable": True,
    },
    "static_slag": {
        "name": "Static Slag",
        "rarity": "Uncommon",
        "kind": "material",
        "coins": 15,
        "xp": 9,
        "zone_ids": ["restaurant_dumpster"],
        "image": "assets/items/static_slag.png",
        "emoji": "🪨",
        "flavor": "Leftover from something catastrophically useful.",
        "pawnable": True,
    },
    "unstable_alloy": {
        "name": "Unstable Alloy",
        "rarity": "Epic",
        "kind": "material",
        "coins": 55,
        "xp": 30,
        "zone_ids": ["mall_rear_lot"],
        "image": "assets/items/unstable_alloy.png",
        "emoji": "⚗️",
        "flavor": "A bad idea forged beautifully.",
        "pawnable": True,
    },

    "iron_gloves": {
        "name": "Iron Gloves",
        "rarity": "Uncommon",
        "kind": "equipment",
        "coins": 30,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/iron_gloves.png",
        "emoji": "🧤",
        "flavor": "Rough forged and ready for deeper digging.",
        "equip_slot": "hands",
        "effects": {"coin_boost": 0.10},
        "equip_bonus": "+10% bonus coins on dive",
        "pawnable": True,
    },
    "magnet_gloves": {
        "name": "Magnet Gloves",
        "rarity": "Rare",
        "kind": "equipment",
        "coins": 60,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/magnet_gloves.png",
        "emoji": "🧲",
        "flavor": "Metal starts finding you first.",
        "equip_slot": "hands",
        "effects": {"drop_bonus": 0.08},
        "equip_bonus": "+8% rare chance on dive",
        "pawnable": True,
    },
    "shockstep_boots": {
        "name": "Shockstep Boots",
        "rarity": "Rare",
        "kind": "equipment",
        "coins": 62,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/shockstep_boots.png",
        "emoji": "🥾",
        "flavor": "Every step feels slightly overclocked.",
        "equip_slot": "feet",
        "effects": {"xp_boost": 0.05},
        "equip_bonus": "+5 flat XP on dive",
        "pawnable": True,
    },
    "greed_magnet": {
        "name": "Greed Magnet",
        "rarity": "Epic",
        "kind": "equipment",
        "coins": 95,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/greed_magnet.png",
        "emoji": "🧲",
        "flavor": "Coins cling to your aura now.",
        "equip_slot": "accessory",
        "effects": {"coin_boost": 0.15},
        "equip_bonus": "+15% coin gain on dive",
        "pawnable": True,
    },
    "glitch_charm": {
        "name": "Glitch Charm",
        "rarity": "Rare",
        "kind": "equipment",
        "coins": 65,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/glitch_charm.png",
        "emoji": "📿",
        "flavor": "It vibrates like it knows a secret route to loot.",
        "equip_slot": "accessory",
        "effects": {"drop_bonus": 0.08},
        "equip_bonus": "+8% bonus rare chance",
        "pawnable": True,
    },
    "rat_king_sigil": {
        "name": "Rat King Sigil",
        "rarity": "Legendary",
        "kind": "equipment",
        "coins": 220,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/rat_king_sigil.png",
        "emoji": "🐀",
        "flavor": "The alley now respects your filth credentials.",
        "equip_slot": "accessory",
        "effects": {"drop_bonus": 0.12},
        "equip_bonus": "+12% extra item chance",
        "pawnable": True,
    },
    "scrap_visor": {
        "name": "Scrap Visor",
        "rarity": "Uncommon",
        "kind": "equipment",
        "coins": 36,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/scrap_visor.png",
        "emoji": "🪖",
        "flavor": "Makes you look dangerous and slightly more clever.",
        "equip_slot": "head",
        "effects": {"xp_boost": 0.06},
        "equip_bonus": "+6% bonus XP on dive",
        "pawnable": True,
    },
    "reinforced_vest": {
        "name": "Reinforced Vest",
        "rarity": "Rare",
        "kind": "equipment",
        "coins": 82,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/reinforced_vest.png",
        "emoji": "🦺",
        "flavor": "A little more armor, a lot more confidence.",
        "equip_slot": "body",
        "effects": {"coin_boost": 0.08},
        "equip_bonus": "+8% coin gain on dive",
        "pawnable": True,
    },

    "golden_potion": {
        "name": "Golden Potion",
        "rarity": "Epic",
        "kind": "consumable",
        "coins": 120,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/golden_potion.png",
        "emoji": "🧃",
        "flavor": "Liquid goblin ambition. Drink responsibly. Or not.",
        "effect_id": "xp_boost",
        "effect_label": "XP Boost",
        "effect_multiplier": 1.5,
        "duration_minutes": 60,
        "use_text": "+50% XP for 1 hour of play",
        "pawnable": True,
    },
    "gremlin_fuel": {
        "name": "Gremlin Fuel",
        "rarity": "Rare",
        "kind": "consumable",
        "coins": 55,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/gremlin_fuel.png",
        "emoji": "⛽",
        "flavor": "Terrible idea. Amazing results.",
        "effect_id": "coin_boost",
        "effect_label": "Coin Boost",
        "effect_multiplier": 1.25,
        "duration_minutes": 60,
        "use_text": "+25% coins for 1 hour of play",
        "pawnable": True,
    },
    "scrapper_tonic": {
        "name": "Scrapper Tonic",
        "rarity": "Uncommon",
        "kind": "consumable",
        "coins": 35,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/scrapper_tonic.png",
        "emoji": "🧪",
        "flavor": "Tastes like bad decisions and loot luck.",
        "effect_id": "rare_boost",
        "effect_label": "Rare Chance Boost",
        "effect_multiplier": 1.10,
        "duration_minutes": 45,
        "use_text": "+10% rare chance for 45 minutes",
        "pawnable": True,
    },
    "stabilizer_gel": {
        "name": "Stabilizer Gel",
        "rarity": "Rare",
        "kind": "consumable",
        "coins": 52,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/stabilizer_gel.png",
        "emoji": "🧴",
        "flavor": "Keeps the weird stuff from exploding. Usually.",
        "effect_id": "double_drop_boost",
        "effect_label": "Double Drop Boost",
        "effect_multiplier": 1.10,
        "duration_minutes": 30,
        "use_text": "+10% extra-item chance for 30 minutes",
        "pawnable": True,
    },

    "overclock_canister": {
        "name": "Overclock Canister",
        "rarity": "Epic",
        "kind": "utility",
        "coins": 75,
        "xp": 10,
        "zone_ids": ["mall_rear_lot"],
        "image": "assets/items/overclock_canister.png",
        "emoji": "🛢️",
        "flavor": "Do not shake. Definitely shake.",
        "pawnable": True,
    },
    "echo_capsule": {
        "name": "Echo Capsule",
        "rarity": "Rare",
        "kind": "utility",
        "coins": 42,
        "xp": 8,
        "zone_ids": ["restaurant_dumpster", "mall_rear_lot"],
        "image": "assets/items/echo_capsule.png",
        "emoji": "🔮",
        "flavor": "Stores sounds from broken timelines.",
        "pawnable": True,
    },
    "lucky_bolt": {
        "name": "Lucky Bolt",
        "rarity": "Rare",
        "kind": "utility",
        "coins": 38,
        "xp": 8,
        "zone_ids": ["apartment_bins", "mall_rear_lot"],
        "image": "assets/items/lucky_bolt.png",
        "emoji": "🍀",
        "flavor": "Probably not lucky. But maybe?",
        "pawnable": True,
    },

    "crown_fragment": {
        "name": "Crown Fragment",
        "rarity": "Rare",
        "kind": "artifact",
        "coins": 0,
        "xp": 20,
        "zone_ids": ["mall_rear_lot"],
        "image": "assets/items/crown_fragment.png",
        "emoji": "👑",
        "flavor": "A shard of very expensive garbage history.",
        "pawnable": False,
        "museum": True,
    },
    "dumpster_core": {
        "name": "Dumpster Core",
        "rarity": "Legendary",
        "kind": "artifact",
        "coins": 0,
        "xp": 45,
        "zone_ids": ["mall_rear_lot"],
        "image": "assets/items/dumpster_core.png",
        "emoji": "🗑️",
        "flavor": "Dense with concentrated alley myth.",
        "pawnable": False,
        "museum": True,
    },
    "dumpster_idol": {
        "name": "Dumpster Idol",
        "rarity": "Epic",
        "kind": "artifact",
        "coins": 0,
        "xp": 35,
        "zone_ids": ["restaurant_dumpster", "mall_rear_lot"],
        "image": "assets/items/dumpster_idol.png",
        "emoji": "🗿",
        "flavor": "It watches. It remembers. It smells bad.",
        "pawnable": False,
        "museum": True,
    },
    "ratfang_token": {
        "name": "Ratfang Token",
        "rarity": "Rare",
        "kind": "artifact",
        "coins": 0,
        "xp": 18,
        "zone_ids": ["restaurant_dumpster", "mall_rear_lot"],
        "image": "assets/items/ratfang_token.png",
        "emoji": "🦷",
        "flavor": "Accepted in no legal economy.",
        "pawnable": False,
        "museum": True,
    },
    "ratwax_seal": {
        "name": "Ratwax Seal",
        "rarity": "Epic",
        "kind": "artifact",
        "coins": 0,
        "xp": 28,
        "zone_ids": ["mall_rear_lot"],
        "image": "assets/items/ratwax_seal.png",
        "emoji": "🕯️",
        "flavor": "Stamped with filthy authority.",
        "pawnable": False,
        "museum": True,
    },

    # ==================== PAWN EXCLUSIVE ITEMS ====================
    # Ultra-rare items only available from Pawn Owner events
    # NOT included in Dirty Draw or normal dive pools
    # Marked with pawn_exclusive=True

    "velvet_static_wings": {
        "name": "Velvet Static Wings",
        "rarity": "Legendary",
        "kind": "secret_artifact",
        "coins": 0,
        "xp": 50,
        "zone_ids": [],
        "image": "assets/items/velvet_static_wings.png",
        "emoji": "🪽",
        "flavor": "Soft to the touch. Buzzes with whispers you can't quite hear.",
        "pawnable": False,
        "pawn_exclusive": True,
    },
    "halo_lost_receipts": {
        "name": "Halo of Lost Receipts",
        "rarity": "Legendary",
        "kind": "secret_artifact",
        "coins": 0,
        "xp": 48,
        "zone_ids": [],
        "image": "assets/items/halo_lost_receipts.png",
        "emoji": "✨",
        "flavor": "A crown made of forgotten transactions. Glows faintly with regret.",
        "pawnable": False,
        "pawn_exclusive": True,
    },
    "echo_charm": {
        "name": "Echo Charm",
        "rarity": "Epic",
        "kind": "secret_artifact",
        "coins": 0,
        "xp": 35,
        "zone_ids": [],
        "image": "assets/items/echo_charm.png",
        "emoji": "🔔",
        "flavor": "Repeats what you wish it wouldn't. Haunting in a cute way.",
        "pawnable": False,
        "pawn_exclusive": True,
    },
    "moonwire_gloves": {
        "name": "Moonwire Gloves",
        "rarity": "Epic",
        "kind": "equipment",
        "coins": 0,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/moonwire_gloves.png",
        "emoji": "🧤",
        "flavor": "Woven from something that isn't quite thread. Glows faintly at night.",
        "equip_slot": "hands",
        "effects": {"rare_chance": 0.20, "xp_boost": 0.10},
        "equip_bonus": "+20% rare find chance, +10% XP",
        "pawnable": False,
        "pawn_exclusive": True,
    },
    "gloomlace_hoodie": {
        "name": "Gloomlace Hoodie",
        "rarity": "Epic",
        "kind": "equipment",
        "coins": 0,
        "xp": 0,
        "zone_ids": [],
        "image": "assets/items/gloomlace_hoodie.png",
        "emoji": "🧥",
        "flavor": "Dark and comfortable. Makes you blend in with the shadows. And yourself.",
        "equip_slot": "body",
        "effects": {"extra_item_chance": 0.15, "coin_boost": 0.12},
        "equip_bonus": "+15% extra items, +12% coins",
        "pawnable": False,
        "pawn_exclusive": True,
    },
    "pocket_eclipse": {
        "name": "Pocket Eclipse",
        "rarity": "Legendary",
        "kind": "secret_artifact",
        "coins": 0,
        "xp": 55,
        "zone_ids": [],
        "image": "assets/items/pocket_eclipse.png",
        "emoji": "🌑",
        "flavor": "A small darkness you can hold. Somehow warm. Somehow kind.",
        "pawnable": False,
        "pawn_exclusive": True,
    },
    "pawns_whisper": {
        "name": "Pawn's Whisper",
        "rarity": "Epic",
        "kind": "secret_artifact",
        "coins": 0,
        "xp": 40,
        "zone_ids": [],
        "image": "assets/items/pawns_whisper.png",
        "emoji": "🤫",
        "flavor": "Sounds like the pawnbroker telling you something you shouldn't know.",
        "pawnable": False,
        "pawn_exclusive": True,
    },
    "lucky_thread_spool": {
        "name": "Lucky Thread Spool",
        "rarity": "Rare",
        "kind": "secret_artifact",
        "coins": 0,
        "xp": 28,
        "zone_ids": [],
        "image": "assets/items/lucky_thread_spool.png",
        "emoji": "🧵",
        "flavor": "Endless thread that tangles itself. But in a good way.",
        "pawnable": False,
        "pawn_exclusive": True,
    },
    "cracked_little_mirror": {
        "name": "Cracked Little Mirror",
        "rarity": "Rare",
        "kind": "secret_artifact",
        "coins": 0,
        "xp": 25,
        "zone_ids": [],
        "image": "assets/items/cracked_little_mirror.png",
        "emoji": "🪞",
        "flavor": "Shows you as you could have been. Or wish you weren't. Unclear.",
        "pawnable": False,
        "pawn_exclusive": True,
    },
    "rat_saint_relic": {
        "name": "Rat Saint Relic",
        "rarity": "Epic",
        "kind": "secret_artifact",
        "coins": 0,
        "xp": 42,
        "zone_ids": [],
        "image": "assets/items/rat_saint_relic.png",
        "emoji": "🐀",
        "flavor": "Holy bones of an unholy rodent. Blessed by the alley.",
        "pawnable": False,
        "pawn_exclusive": True,
    },
    "soft_engine_heart": {
        "name": "Soft Engine Heart",
        "rarity": "Legendary",
        "kind": "secret_artifact",
        "coins": 0,
        "xp": 52,
        "zone_ids": [],
        "image": "assets/items/soft_engine_heart.png",
        "emoji": "💓",
        "flavor": "Mechanical and tender at once. Still beating faintly. Don't ask why.",
        "pawnable": False,
        "pawn_exclusive": True,
    },
    "midnight_broadcast_tape": {
        "name": "Midnight Broadcast Tape",
        "rarity": "Epic",
        "kind": "secret_artifact",
        "coins": 0,
        "xp": 38,
        "zone_ids": [],
        "image": "assets/items/midnight_broadcast_tape.png",
        "emoji": "📼",
        "flavor": "A recording from a station that doesn't exist. Play it anyway.",
        "pawnable": False,
        "pawn_exclusive": True,
    },
    "thread_hollow_coat": {
        "name": "Thread of the Hollow Coat",
        "rarity": "Rare",
        "kind": "secret_artifact",
        "coins": 0,
        "xp": 30,
        "zone_ids": [],
        "image": "assets/items/thread_hollow_coat.png",
        "emoji": "🧵",
        "flavor": "A single thread from a coat that contains everything. And nothing.",
        "pawnable": False,
        "pawn_exclusive": True,
    },
    "glass_eye_alley_mercy": {
        "name": "Glass Eye of Alley Mercy",
        "rarity": "Legendary",
        "kind": "secret_artifact",
        "coins": 0,
        "xp": 60,
        "zone_ids": [],
        "image": "assets/items/glass_eye_alley_mercy.png",
        "emoji": "👁️",
        "flavor": "Watches over the forgotten. Never blinks. Always cares.",
        "pawnable": False,
        "pawn_exclusive": True,
    },
}

DIRTY_DRAW_POOL = [
    {"item_id": "mystery_box", "weight": 8},
    {"item_id": "glitch_charm", "weight": 5},
    {"item_id": "greed_magnet", "weight": 4},
    {"item_id": "broken_phone", "weight": 6},
    {"item_id": "burnt_sludge", "weight": 3},
    {"item_id": "scrap_metal", "weight": 10},
]

DAILY_QUEST_TEMPLATES = [
    {
        "quest_key": "dive_master",
        "name": "Dumpster Diver",
        "description": "Complete 3 dives.",
        "quest_type": "dive_count",
        "target": 3,
        "reward_coins": 200,
        "reward_tickets": 0,
        "zone_id": "back_alley",
        "time": "morning",
        "difficulty": 1,
        "flavor_text": "Fresh finds. Early moods. Get out there.",
    },
    {
        "quest_key": "junk_dealer",
        "name": "Junk Dealer",
        "description": "Pawn 2 pawnable items.",
        "quest_type": "pawn_count",
        "target": 2,
        "reward_coins": 100,
        "reward_tickets": 1,
        "zone_id": "apartment_bins",
        "time": "evening",
        "difficulty": 2,
        "flavor_text": "The pawnbroker's dealing late tonight. Strike while they're in a good mood.",
    },
    {
        "quest_key": "coin_hustle",
        "name": "Coin Hustle",
        "description": "Earn 300 coins from dives.",
        "quest_type": "earn_coins",
        "target": 300,
        "reward_coins": 250,
        "reward_tickets": 0,
        "zone_id": "restaurant_dumpster",
        "time": "night",
        "difficulty": 3,
        "flavor_text": "The back alleys are flowing with cash tonight. If you're brave enough.",
    },
    {
        "quest_key": "gear_up",
        "name": "Gear Up",
        "description": "Equip 1 item.",
        "quest_type": "equip_item",
        "target": 1,
        "reward_coins": 150,
        "reward_tickets": 0,
        "zone_id": "back_alley",
        "time": "morning",
        "difficulty": 1,
        "flavor_text": "Dress for the dumpster you want, not the dumpster you have.",
    },
    {
        "quest_key": "luxury_hunt",
        "name": "Luxury Hunt",
        "description": "Complete 2 dives in high-tier zones.",
        "quest_type": "dive_count",
        "target": 2,
        "reward_coins": 350,
        "reward_tickets": 1,
        "zone_id": "mall_rear_lot",
        "time": "night",
        "difficulty": 4,
        "flavor_text": "Elite trash only. The mall rear lot is calling your name.",
    },
    {
        "quest_key": "scrapper_grind",
        "name": "Scrapper's Grind",
        "description": "Earn 500 coins total.",
        "quest_type": "earn_coins",
        "target": 500,
        "reward_coins": 400,
        "reward_tickets": 2,
        "zone_id": "restaurant_dumpster",
        "time": "evening",
        "difficulty": 5,
        "flavor_text": "This is a real money-maker's job. You got this.",
    },
]

WEEKEND_EVENTS = [
    {
        "key": "rat_kings_blessing",
        "name": "Rat King's Blessing",
        "emoji": "🐀",
        "type": "weekend",
        "profile_line": "Rats are hoarding shiny nonsense all weekend.",
        "description": "Bonus extra-item chance. The alley is squeaking with greed.",
        "coin_multiplier": 1.0,
        "xp_multiplier": 1.0,
        "extra_item_chance": 0.20,
        "rare_bonus": 0.03,
        "event_item_id": None,
    },
    {
        "key": "gold_rush",
        "name": "Gold Rush Weekend",
        "emoji": "💰",
        "type": "weekend",
        "profile_line": "Coins are hitting different right now.",
        "description": "+50% coins on all dives this weekend.",
        "coin_multiplier": 1.5,
        "xp_multiplier": 1.0,
        "extra_item_chance": 0.0,
        "rare_bonus": 0.02,
        "event_item_id": None,
    },
    {
        "key": "unstable_mix",
        "name": "Unstable Mix Weekend",
        "emoji": "🧪",
        "type": "weekend",
        "profile_line": "The bench is hissing. Good sign honestly.",
        "description": "Mixing gets a little more chaotic and a little more rewarding.",
        "coin_multiplier": 1.0,
        "xp_multiplier": 1.0,
        "extra_item_chance": 0.10,
        "rare_bonus": 0.05,
        "event_item_id": None,
    },
    {
        "key": "dumpster_fire",
        "name": "Dumpster Fire",
        "emoji": "🔥",
        "type": "weekend",
        "profile_line": "Everything is mildly on fire and wildly profitable.",
        "description": "+30% XP. Small chance to find Burned Scrap.",
        "coin_multiplier": 1.0,
        "xp_multiplier": 1.3,
        "extra_item_chance": 0.0,
        "rare_bonus": 0.03,
        "event_item_id": "burned_scrap",
    },
]

SEASONAL_EVENTS = [
    {
        "key": "cursed_trash",
        "name": "Cursed Trash",
        "emoji": "🎃",
        "type": "seasonal",
        "months": [10],
        "profile_line": "The dumpsters are whispering again.",
        "description": "Spooky pulls and cursed flavor all month.",
        "coin_multiplier": 1.0,
        "xp_multiplier": 1.15,
        "extra_item_chance": 0.05,
        "rare_bonus": 0.04,
        "event_item_id": None,
    },
    {
        "key": "frozen_finds",
        "name": "Frozen Finds",
        "emoji": "❄️",
        "type": "seasonal",
        "months": [12, 1],
        "profile_line": "The loot is cold but weirdly premium.",
        "description": "Icy pulls, calmer chaos, and occasional Frozen Phone drops.",
        "coin_multiplier": 1.0,
        "xp_multiplier": 1.1,
        "extra_item_chance": 0.05,
        "rare_bonus": 0.05,
        "event_item_id": "frozen_phone",
    },
    {
        "key": "broken_reality",
        "name": "Broken Reality",
        "emoji": "🃏",
        "type": "seasonal",
        "months": [4],
        "profile_line": "Nothing feels correct and that kind of rules.",
        "description": "Luck spikes, labels feel cursed, and loot tables get goofy.",
        "coin_multiplier": 1.0,
        "xp_multiplier": 1.0,
        "extra_item_chance": 0.10,
        "rare_bonus": 0.06,
        "event_item_id": None,
    },
]

HELP_TEXT = (
    "• **Dive** runs a multi-step scavenging sequence with random chaos.\n"
    "• **Loot** lets you inspect items and use potions / equip crafted gear.\n"
    "• **Mix** opens the goblin lab with fixed recipes and chaos mixing.\n"
    "• **Zones** is an interactive map where you can set your active zone.\n"
    "• **Events** shows the live weekend and seasonal world modifiers."
)



def get_active_weekend_event(now: datetime | None = None) -> dict | None:
    now = now or datetime.utcnow()
    if now.weekday() not in {4, 5, 6}:
        return None
    return WEEKEND_EVENTS[now.isocalendar().week % len(WEEKEND_EVENTS)]



def get_active_seasonal_event(now: datetime | None = None) -> dict | None:
    now = now or datetime.utcnow()
    for event in SEASONAL_EVENTS:
        if now.month in event["months"]:
            return event
    return None



def get_live_events(now: datetime | None = None) -> list[dict]:
    now = now or datetime.utcnow()
    live: list[dict] = []
    weekend = get_active_weekend_event(now)
    seasonal = get_active_seasonal_event(now)
    if weekend:
        live.append(weekend)
    if seasonal:
        live.append(seasonal)
    return live

MUSEUM_COLLECTIONS = {
    "salvaged_basics": {
        "name": "Salvaged Basics",
        "emoji": "🧩",
        "description": "The humble scraps that started every great alley career.",
        "item_ids": [
            "old_shoe",
            "scrap_metal",
            "compressed_scrap_cube",
            "bent_nail_cluster",
            "scuffed_plastic_shard",
            "cracked_wire_bundle",
            "dusty_gear_chunk",
            "burnt_sludge",
            "fused_trash_lump",
        ],
    },
    "tech_relics": {
        "name": "Tech Relics",
        "emoji": "⚡",
        "description": "Recovered circuitry, batteries, and buzzing weirdness.",
        "item_ids": [
            "broken_phone",
            "static_coil",
            "rustcore_plate",
            "bent_circuit",
            "melted_trinket",
            "neon_relay",
            "distorted_battery",
            "balance_chip",
            "foam_insulator",
            "static_slag",
        ],
    },
    "glitched_objects": {
        "name": "Glitched Objects",
        "emoji": "🧪",
        "description": "Unstable artifacts produced when trash stops behaving correctly.",
        "item_ids": [
            "glitch_resin",
            "neon_shard",
            "stabilizer_gel",
            "unstable_alloy",
            "overclock_canister",
            "echo_capsule",
            "lucky_bolt",
            "bonus_socket",
            "volatile_battery",
        ],
    },
    "rat_market": {
        "name": "Rat Market Curios",
        "emoji": "🐀",
        "description": "Odd valuables whispered through the alley trade routes.",
        "item_ids": [
            "ratfang_token",
            "greed_magnet",
            "ratwax_seal",
            "dumpster_core",
        ],
    },
    "crafted_gear": {
        "name": "Crafted Gear",
        "emoji": "🧥",
        "description": "Proof that enough junk and bad ideas can become equipment.",
        "item_ids": [
            "iron_gloves",
            "shockstep_boots",
            "magnet_gloves",
            "glitch_charm",
            "golden_potion",
        ],
    },
    "crown_artifacts": {
        "name": "Crown Artifacts",
        "emoji": "👑",
        "description": "Prestige relics revered by the filthiest elite.",
        "item_ids": [
            "mystery_box",
            "trash_crown",
            "rat_king_sigil",
            "dumpster_idol",
        ],
    },
}

MUSEUM_ARTIFACT_TEXT = {
    "old_shoe": {
        "origin": "Usually recovered from beginner dives in the Back Alley.",
        "museum_text": "A discarded classic. Every scrapper remembers their first one.",
    },
    "scrap_metal": {
        "origin": "Commonly pulled from alleys and apartment bins.",
        "museum_text": "The backbone of the junk economy.",
    },
    "broken_phone": {
        "origin": "Recovered from household piles and unstable mixes.",
        "museum_text": "Dead screen. Immortal aura.",
    },
    "mystery_box": {
        "origin": "Found in advanced zones and premium transformations.",
        "museum_text": "Nobody agrees on where these come from. Everyone wants one.",
    },
    "trash_crown": {
        "origin": "Recovered from elite lots or reforged from crown fragments.",
        "museum_text": "Proof that garbage can achieve royalty.",
    },
    "dumpster_idol": {
        "origin": "Assembled through advanced refinement and prestige mixing.",
        "museum_text": "A sacred monument to the underground trash age.",
    },
}
